In [ ]:
import numpy as np

In [3]:
import numpy as np

#create a 3 * 3 matrix
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
#Matrix B is a 3x3 identity matrix 
# (a diagonal matrix with ones on the diagonal).
B = np.array([
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
])
#Compute the matrix product of A and B and 
# store the result in a matrix C.
C = np.dot(A, B)
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
#C = np.dot(A, B)
#Add 5 to each element of matrix C.
matrix_C_new = C + 5
print(matrix_C_new)

[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [5]:
#Compute the square root of each element in the 
# modified matrix C.
C_sqrt = np.sqrt(matrix_C_new)
print(C_sqrt)

[[2.44948974 2.64575131 2.82842712]
 [3.         3.16227766 3.31662479]
 [3.46410162 3.60555128 3.74165739]]


In [6]:
# Compute the sum of each row in matrix 
# C and store the result in a 1D NumPy array row_sums.

#sum of each row
row_sum = np.sum(matrix_C_new, axis = 1)
print(row_sum)

[21 30 39]


In [9]:
#sum of columns
column_sum = np.sum(matrix_C_new, axis = 0)
print(column_sum)

[27 30 33]


In [10]:
# Transpose the matrix C and then 
# flatten it into a 1D array.
C_Transpose = matrix_C_new.T
print(C_Transpose)

[[ 6  9 12]
 [ 7 10 13]
 [ 8 11 14]]


In [12]:
#flatten into 1D array
C_flatten = C_Transpose.flatten
print(C_flatten())

[ 6  9 12  7 10 13  8 11 14]


In [13]:
#Compute the determinant of matrix A.
#HINT: np.linalg.det()
det_A = np.linalg.det(A)
print("Determinant of A:", det_A)


Determinant of A: -9.51619735392994e-16


In [14]:
#Compute the eigenvalues and eigenvectors of matrix A.
#HINT: np.linalg.eig()

# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)


Eigenvalues:
 [ 1.61168440e+01 -1.11684397e+00 -4.29954797e-16]

Eigenvectors:
 [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [15]:
# Create a function normalize_matrix(mat) that 
# normalizes the input matrix such that the minimum value is 0 and the maximum value is 1. Apply this function to matrix C.
#HINT: normalized_C = np.min() / np.max()
#normalized_C = np.min() / np.max()
def normalize_matrix(mat):
    min_val = np.min(mat)
    max_val = np.max(mat)
    
    normalized = (mat - min_val) / (max_val - min_val)
    return normalized
    
normalized_C = normalize_matrix(matrix_C_new)

print("Normalized Matrix C:\n", normalized_C)


Normalized Matrix C:
 [[0.    0.125 0.25 ]
 [0.375 0.5   0.625]
 [0.75  0.875 1.   ]]
