In [2]:
import numpy as np

In [3]:
# create a 1-dimensional array
arr1 = np.array([1, 2, 3])
print("Rank 1 array")
print(arr1)

# get the data type of the entire array
print(type(arr1))

# get the data type of the items in the array
print(arr1.dtype)

# get the shape of the array
print(arr1.shape)

# retrieve each item in the array using indexing
print(arr1[0], arr1[1], arr1[2])

# Reassign value to the item in index 2 to 4
arr1[2] = 4
print(arr1)

Rank 1 array
[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1 2 3
[1 2 4]


In [4]:
# create a 2-dimension array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print("\nRank 2 array")
print(arr2)

# get the data type of the entire array
print(type(arr2))

# get the data type of the items in the array
print(arr2.dtype)

# get the shape of the array
print(arr2.shape)

# retrieve 1st item in the 1st list
print(arr2[0, 0])

# retrieve 2nd item in the 1st list
print(arr2[0, 1])

# retrieve 1st item in the 2nd list
print(arr2[1, 0])

# retrieve the second list
print(arr2[-1])


Rank 2 array
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
int64
(2, 3)
1
2
4
[4 5 6]


In [5]:
# create a nested array using the ndmin key for minimum dimension
arr3 = np.array(np.arange(0, 6), ndmin=2)
print("\nRank 3 array")
print(arr3)

# get the data type of the entire array
print(type(arr3))

# get the data type of the items in the array
print(arr3.dtype)

# get the shape of the array
print(arr3.shape)

# retrieve 1st item in the nested array
print(arr3[0, 0])

# retrieve 2nd item in the nested array
print(arr3[0, 1])

# retrieve 3rd item in the nested array
print(arr3[0, 2])

# retrieve the inner array
print(arr3[-1])


Rank 3 array
[[0 1 2 3 4 5]]
<class 'numpy.ndarray'>
int64
(1, 6)
0
1
2
[0 1 2 3 4 5]


In [6]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2, 2))
print("Zero array")
print(zero)

# create an array of ones with 1 dim and size of 2 each
one = np.ones((1, 2))
print("\nOnes array")
print(one)

# create a new array with given shape, type, and filled with 5 as the value
constant = np.full((2, 2), 5)
print("\nConstant array")
print(constant)

# create a 2-D array with 1 on the diagonal and 0 in other positions
diag1 = np.eye(3)
print("\nDiagonal ones array")
print(diag1)

# diag start at index 1
diag = np.eye(4, k=1)
print("\nShifted diagonal ones array")
print(diag)

# create an array with random values
rand = np.random.random((2, 2))
print("\nRandom array")
print(rand)

# Generate 10 evenly spaced numbers between 0 and 1, excluding the endpoint
even_spaced = np.linspace(0, 1, num=10)
print("\nEvenly Spaced array")
print(even_spaced)

Zero array
[[0. 0.]
 [0. 0.]]

Ones array
[[1. 1.]]

Constant array
[[5 5]
 [5 5]]

Diagonal ones array
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

Shifted diagonal ones array
[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]

Random array
[[0.67962418 0.54905176]
 [0.25977655 0.2826111 ]]

Evenly Spaced array
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [7]:
# Reshaped into a 2x3 (2 rows, 3 columns)
print("Original array: ", arr3)

arr_reshaped = arr3.reshape(2, 3)

print("Reshaped array (2x3):\n", arr_reshaped)

Original array:  [[0 1 2 3 4 5]]
Reshaped array (2x3):
 [[0 1 2]
 [3 4 5]]


In [9]:
# create a 2-dimension array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Resizing to a bigger array - this will repeat the first row of the array
arr_resized = np.resize(arr, (3, 3))

arr_resized

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [10]:
# Flatten the array
flattened = arr_resized.flatten()
print("Flattened array:", flattened)

Flattened array: [1 2 3 4 5 6 1 2 3]


In [11]:
# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Use the flat iterator to iterate over each element
for element in arr.flat:
    print(element)

1
2
3
4
5
6


Challenge:What are the primary risks to data integrity 
when flattening a NumPy array? Specifically, explain the 
difference between a 'view' and a 'copy', and how using. ravel() VS  .flatten() method  
can lead to accidental data mutation or memory errors.

=> The main data integrity risk when flattening is unintended 
sharing of memory. A view shares the original array’s data, 
so changing it can mutate the source. A copy has its own 
memory, so changes stay isolated. ravel() often returns 
a view, making it faster and more memory-efficient but 
riskier. flatten() always returns a copy, making it safer 
for modification but more memory-expensive.

In [12]:
transposed = arr.reshape(2, 3).T
print("Transposed array:")
print(transposed)

Transposed array:
[[1 4]
 [2 5]
 [3 6]]


In [13]:
# create a 2x3 array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Create another array to concatenate
arr2 = np.array([[12, 13, 14], [15, 16, 17], [18, 19, 20]])

# Concatenate along rows (axis=0)
concatenated = np.concatenate((arr, arr2), axis=0)
print("Concatenated along rows:\n", concatenated)

# Stack arrays vertically (vstack)
vstacked = np.vstack((arr, arr2))
print("Vertically stacked:\n", vstacked)

Concatenated along rows:
 [[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [15 16 17]
 [18 19 20]]
Vertically stacked:
 [[ 1  2  3]
 [ 4  5  6]
 [12 13 14]
 [15 16 17]
 [18 19 20]]


Challenge:
Concatenation is a general operation that joins arrays 
along a specified axis, while vertical stacking is a 
specialized operation that stacks arrays along the first axis 
(rows) and ensures inputs are at least 2D.
They produce different results when working with 1D arrays, higher-dimensional arrays, or when axis control is required, because vstack() reshapes inputs and enforces row-wise stacking, while concatenate() preserves the original dimensionality and allows flexible axis selection.

In [14]:
import numpy as np

# Create an array with repeated elements
dup_arr = np.array([1, 2, 2, 3, 4, 4, 4, 5, 5, 6])

# Find the unique elements
unique_elements = np.unique(dup_arr)
print("Unique elements:", unique_elements)

# Find the unique elements and their counts
unique_elements, counts = np.unique(dup_arr, return_counts=True)
print("Unique elements:", unique_elements)
print("Counts of each unique element:", counts)

# Find the unique elements and the indices of the first occurrence
unique_elements, indices = np.unique(dup_arr, return_index=True)
print("Unique elements:", unique_elements)
print("Indices of first occurrence:", indices)

Unique elements: [1 2 3 4 5 6]
Unique elements: [1 2 3 4 5 6]
Counts of each unique element: [1 2 1 3 2 1]
Unique elements: [1 2 3 4 5 6]
Indices of first occurrence: [0 1 3 4 7 9]


In [16]:
import numpy as np

# Create a 1D array
arr = np.arange(12)
print("Original array:", arr)

# Reshape to a 3x4 array
reshaped_arr = np.reshape(arr, (3, 4))
print("Reshaped array (3x4):\n", reshaped_arr)

# Basic Indexing
# Extract a single element
element = reshaped_arr[1, 2]  # Element at row 1, column 2
print("Element at indices(1, 2):", element)

# Slicing
# Slice a subarray
subarray = reshaped_arr[:, 1:3]  # All rows, columns 1 and 2
print("Subarray (columns 1 and 2):\n", subarray)

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at indices(1, 2): 6
Subarray (columns 1 and 2):
 [[ 1  2]
 [ 5  6]
 [ 9 10]]


In [17]:
# Use fancy indexing to select elements at specific row and column indices
row_indices = [0, 1, 2] # First, second, and third rows
col_indices = [2, 1, 0] # Third, second, and first columns

selected_elements = reshaped_arr[row_indices, col_indices]
print("Selected_elements using fancy indexing:", selected_elements)

Selected_elements using fancy indexing: [2 5 8]


In [18]:
# Create a boolean indexing mask
mask = reshaped_arr > 5 # filter elements that are greater than 5
print("Boolean mask:\n", mask)

# Use the mask to select elements
filtered = reshaped_arr[mask]
print("Filtered elements (greater than 5):", filtered)

Boolean mask:
 [[False False False False]
 [False False  True  True]
 [ True  True  True  True]]
Filtered elements (greater than 5): [ 6  7  8  9 10 11]


In [19]:
# Element-wise addition
added = reshaped_arr + 10
print("Array after adding 10 to each element:\n", added)

# Element-wise multiplication
multiplied = reshaped_arr * 2
print("Array after multiplying each element by 2:\n", multiplied)

Array after adding 10 to each element:
 [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
Array after multiplying each element by 2:
 [[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]]


In [20]:

# Dot product
# Create two 1D arrays (vectors)
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])

# Compute the dot product
dot_product = np.dot(vec1, vec2)
print("Dot product of vec1 and vec2:", dot_product)

"""
Dot Product: The dot product is computed as 1*4 + 2*5 + 3*6 = 32. 
This is a scalar value, not an array.
"""

Dot product of vec1 and vec2: 32


'\nDot Product: The dot product is computed as 1*4 + 2*5 + 3*6 = 32. \nThis is a scalar value, not an array.\n'

In [21]:
# Create two 2D arrays (matrices)
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])

# Compute the matrix product using np.matmul()
matrix_product = np.matmul(mat1, mat2)
print("Matrix product using np.matmul():\n", matrix_product)

Matrix product using np.matmul():
 [[19 22]
 [43 50]]


Challenge: Apply dot product operation to mat1 and mat2.
 Compare results to np.matmul.
 Both np.dot() and np.matmul() perform matrix multiplication 
 when applied to 2D arrays.

In [22]:

# Define two matrices
mat1 = np.array([[1, 2, 3],
                 [4, 5, 6]])

mat2 = np.array([[7, 8],
                 [9, 10],
                 [11, 12]])

# Apply dot product
dot_result = np.dot(mat1, mat2)

# Apply matrix multiplication
matmul_result = np.matmul(mat1, mat2)

# Print results
print("Dot Product Result:\n", dot_result)
print("\nMatrix Multiplication (matmul) Result:\n", matmul_result)

Dot Product Result:
 [[ 58  64]
 [139 154]]

Matrix Multiplication (matmul) Result:
 [[ 58  64]
 [139 154]]


In [23]:
# NumPy has built-in support of broadcasting
a = np.array([[1], [2], [3]])
b = np.array([4, 5, 6])

# add each value from a to each element of b
c = a + b
print("C: \n", c)

# This is the same broadcasting process as above but using np.broadcast() function
bc = np.broadcast(a, b)
x = np.zeros(bc.shape)
x.flat = [a + b for (a, b) in bc]
print("X: \n", x)

C: 
 [[5 6 7]
 [6 7 8]
 [7 8 9]]
X: 
 [[5. 6. 7.]
 [6. 7. 8.]
 [7. 8. 9.]]


In [24]:
# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the mean (average) of the array
mean_value = np.mean(arr)
print("Mean:", mean_value)

# Calculate the median of the array - middle value of the sorted array.
median_value = np.median(arr)
print("Median:", median_value)

# Calculate the standard deviation of the array
# - measures the amount of variation or dispersion of the elements in the array
std_dev = np.std(arr)
print("Standard Deviation:", std_dev)

# Find the minimum value in the array
min_value = np.min(arr)
print("Minimum value:", min_value)

# Find the maximum value in the array
max_value = np.max(arr)
print("Maximum value:", max_value)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Minimum value: 1
Maximum value: 10
