In [1]:
import numpy as np

In [2]:
dt = np.array(range(1, 10))
print(dt.dtype)
dt

int64


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
dt_1 = np.array(range(1, 10), dtype=np.float64)
print(dt_1.dtype)
dt_1

float64


array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [4]:
import numpy as np

In [5]:
# create structured data type
dt = np.dtype([('name', 'U20'), ('age', np.int64), ('points', np.float64)])
print(dt)

# <U20 is a Unicode string with a maximum length of 20 characters
# <i8 is a 64-bit integer
# <f8 is a 64-bit float

# apply it to ndarray object called student
student = np.array([('student_A', 20, 100),
                    ('student_B_has_a_very_long_name', 20, 98),
                    ('student_C', 21, 95)], dtype=dt)

student

[('name', '<U20'), ('age', '<i8'), ('points', '<f8')]


array([('student_A', 20, 100.), ('student_B_has_a_very', 20,  98.),
       ('student_C', 21,  95.)],
      dtype=[('name', '<U20'), ('age', '<i8'), ('points', '<f8')])

In [6]:
# To access content of age column
student['age']

array([20, 20, 21])

In [7]:
#To access content of name column
student['name']

array(['student_A', 'student_B_has_a_very', 'student_C'], dtype='<U20')

In [8]:
#To access content of points column
student['points']

array([100.,  98.,  95.])

Challenge answers:
Challenge: What are the primary use cases 
for multi-dimensional arrays, and why does NumPy’s 
contiguous memory 
allocation outperform Python's nested lists?"
Primary use cases of multi-dimensional array are data analysis, machine learning
image processing, scientific computing where data is structured in grids or matrices.

Why NumPy is faster:
NumPy arrays use contiguous memory allocation, allowing 
efficient CPU caching, vectorization, and execution 
in C code, whereas Python nested lists store elements as separate objects 
with pointers, leading to slower performance.